### ISSUE TITLE
Don't accept transactions with non consecutive nonce

### ISSUE THREAD

**Issue by grzegorz225** [aeternity/elixir-node#714] opened 2018-10-29 23:38 UTC
While testing compatibility of withdraw and deposit tx with my tool(https://github.com/aeternity/elixir-node/issues/713) I noticed that epoch fails to mine the ChannelCreateTx.

The ChannelCreateTx is properly gossiped to every node in the network. In every elixir node Miner.candidate contains the ChannelCreateTx as expected. The problem is that when epoch tries to mine a block the ChannelCreateTx is not being included in the block as it does not validate.

The epoch logs contain the reason why ChannelCreateTx is not mined:
```
2018-10-29 23:58:01.319 [debug] <0.5788.0>@aec_trees:apply_txs_on_state_trees:276 Tx {aetx,channel_create_tx,aesc_create_tx,{channel_create_tx,{id,account,<<177,200,2,169,77,161,103,38,251,213,241,29,89,5,39,70,169,38,227,34,65,209,163,113,54,48,187,86,18,9,228,159>>},100,{id,account,<<86,153,201,210,211,197,179,33,24,213,195,169,97,199,198,169,43,93,55,18,202,186,118,60,237,231,25,44,73,177,224,214>>},100,5,2,0,1,<<216,210,41,252,196,75,135,247,38,209,40,199,125,2,87,26,206,201,146,15,201,5,232,243,206,90,139,218,124,255,42,72>>,2}} cannot be applied due to an error account_nonce_too_low
``` 
The nonce of the transaction is 2. The transaction in question is:
```
%Aecore.Tx.SignedTx{
    data: %Aecore.Tx.DataTx{
      fee: 1,
      nonce: 2,
      payload: %Aecore.Channel.Tx.ChannelCreateTx{
        channel_reserve: 5,
        initiator_amount: 100,
        locktime: 2,
        responder_amount: 100,
        state_hash: <<216, 210, 41, 252, 196, 75, 135, 247, 38, 209, 40, 199,
          125, 2, 87, 26, 206, 201, 146, 15, 201, 5, 232, 243, 206, 90, 139,
          218, 124, 255, 42, 72>>
      },
      senders: [
        %Aecore.Chain.Identifier{
          type: :account,
          value: <<177, 200, 2, 169, 77, 161, 103, 38, 251, 213, 241, 29, 89, 5,
            39, 70, 169, 38, 227, 34, 65, 209, 163, 113, 54, 48, 187, 86, 18, 9,
            228, 159>>
        },
        %Aecore.Chain.Identifier{
          type: :account,
          value: <<86, 153, 201, 210, 211, 197, 179, 33, 24, 213, 195, 169, 97,
            199, 198, 169, 43, 93, 55, 18, 202, 186, 118, 60, 237, 231, 25, 44,
            73, 177, 224, 214>>
        }
      ],
      ttl: 0,
      type: Aecore.Channel.Tx.ChannelCreateTx
    },
    signatures: [
      <<10, 232, 22, 233, 130, 133, 12, 219, 190, 211, 249, 84, 203, 44, 167,
        111, 75, 48, 225, 188, 129, 187, 62, 2, 188, 165, 90, 110, 150, 65, 252,
        63, 149, 164, 215, 9, 29, 135, 46, 35, 122, 194, 228, 132, 39, 173,
        ...>>,
      <<42, 110, 66, 245, 204, 21, 107, 26, 95, 51, 195, 148, 169, 125, 149,
        181, 131, 39, 63, 103, 248, 226, 183, 163, 8, 11, 116, 192, 201, 30, 18,
        125, 36, 53, 133, 129, 35, 155, 191, 154, 16, 197, 97, 16, 102, ...>>
    ]
  }
```
The account states are as following:
```
[
  {<<206, 167, 173, 228, 112, 201, 249, 157, 157, 78, 64, 8, 128, 168, 111, 29,
     73, 187, 68, 75, 98, 241, 26, 158, 187, 100, 187, 207, 235, 115, 254,
     243>>,
   %Aecore.Account.Account{
     balance: 100000000000001,
     id: %Aecore.Chain.Identifier{type: :account, value: ""},
     nonce: 0
   }},
  {<<177, 200, 2, 169, 77, 161, 103, 38, 251, 213, 241, 29, 89, 5, 39, 70, 169,
     38, 227, 34, 65, 209, 163, 113, 54, 48, 187, 86, 18, 9, 228, 159>>,
   %Aecore.Account.Account{
     balance: 10000000000000000000,
     id: %Aecore.Chain.Identifier{type: :account, value: ""},
     nonce: 0
   }},
  {<<111, 218, 126, 13, 247, 233, 226, 139, 144, 77, 160, 136, 115, 103, 121,
     184, 132, 156, 109, 185, 4, 20, 219, 120, 46, 204, 68, 45, 124, 56, 130,
     187>>,
   %Aecore.Account.Account{
     balance: 40000000000000000000,
     id: %Aecore.Chain.Identifier{type: :account, value: ""},
     nonce: 0
   }},
  {<<86, 153, 201, 210, 211, 197, 179, 33, 24, 213, 195, 169, 97, 199, 198, 169,
     43, 93, 55, 18, 202, 186, 118, 60, 237, 231, 25, 44, 73, 177, 224, 214>>,
   %Aecore.Account.Account{
     balance: 10000000000000000000,
     id: %Aecore.Chain.Identifier{type: :account, value: ""},
     nonce: 0
   }},
  {<<42, 189, 247, 220, 241, 153, 58, 46, 112, 170, 174, 20, 63, 27, 212, 247,
     20, 205, 4, 157, 67, 178, 76, 10, 228, 245, 9, 151, 76, 21, 212, 7>>,
   %Aecore.Account.Account{
     balance: 160000000000000000000,
     id: %Aecore.Chain.Identifier{type: :account, value: ""},
     nonce: 0
   }},
  {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0>>,
   %Aecore.Account.Account{
     balance: 10000000000000000000,
     id: %Aecore.Chain.Identifier{type: :account, value: ""},
     nonce: 0
   }}
]
```
Every account has a nonce of zero. The senders of the tx have sufficient funds. The transaction should validate. I will need to dig into epoch code to find out what causes the issue.

Steps to reproduce:
1) Create 3 epoch nodes and 3 elixir nodes. Stop mining in every node.
2) Connect all nodes together.
3) Resume mining in elixir node 1 -> Stop mining at block_height = 1
4) Make sure that the block was registered by all nodes
5) Resume mining in elixir node 2 -> Stop mining at block_height = 2
6) Make sure that the block was registered by all nodes
7) Resume mining in epoch node 1
8) Make sure that the next blocks are properly registered by all nodes
9) Try to establish a state channel between elixir node 1 and elixir node 2 using steps 1-7 in the following docs (https://github.com/aeternity/elixir-node/blob/master/docs/aeternity-erlang-compatibility.md#standard-scenario) using 2 as the nonce
10) Make sure that ChannelCreateTx was broadcasted to every node
11) Each elixir node should contain ChannelCreateTx in Miner.candidate
12) Epoch won't mine the transaction as the nonce is too small (the nonce in tx is 2 but the account nonce is = 0)

**Comment by grzegorz225** [comment] 2018-10-29 23:56
This issue is caused by the fact that epoch threats transactions with a nonce different from prev_nonce+1 as invalid transactions:
https://github.com/aeternity/epoch/blob/v0.16.0/apps/aetx/src/aetx_utils.erl#L82
https://github.com/aeternity/epoch/blob/v0.16.0/apps/aecore/src/aec_tx_pool.erl#L475

**Comment by cytadela8** [comment] 2018-10-30 00:10
@grzegorz225 I would like to suggest closing this issue or completely changing description. This is not a channel related problem. The transaction wasn't accepted by epoch, because you choose nonce "2" instead of "1" in step 9. The transaction was accepted by our code due to the checks in DataTx. So this problem should be reproducible with any transaction. The description should also state clearly that it's a validation problem.

**Comment by cytadela8** [comment] 2018-10-30 00:11
Or maybe just make the one line fix + one test and PR without producing tons of documentation about this small mistake.

**Comment by thepiwo** [comment] 2018-10-31 09:33
closed by https://github.com/aeternity/elixir-node/pull/715

**Closed by thepiwo** 2018-10-31 09:33 UTC
Labels: 0.16, bug, spec-adjust
