### ISSUE TITLE
fix nakamoto consensus

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-node#451] opened 2018-06-28 10:38 UTC
allow chain to be overwritten by longer ones

**Comment by cytadela8** [comment] 2018-06-29 13:30
Doesn't this work? We keep track of top_block (longest chain) and forks should work as expected.

**Comment by cytadela8** [comment] 2018-06-29 13:35
I found the discussion in #414. So I guess the problem is unknown and due to some changes since I last worked with that.

**Comment by gspasov** [comment] 2018-08-31 07:51
I think this is fixed with #567

**Comment by thepiwo** [comment] 2018-08-31 07:53
yes can be, let's assume it will be resolved and reopen another issue if the problem persists

**Closed** 2018-09-05 13:07 UTC
Labels: bug, non-spec
